--[[ Welcome SKidder ]]--
local _G = _G
_G = nil
local debug = debug
debug = nil

do
    if UwU then
        do while true do return error("[Detect]: Bruh"), false end end
    elseif not UwU then
        do
            local UwU = "UwU"
            do
                local Name = UwU
                return Name
            end
        end
    else
        do while true do return error("[Detect]: Bruh"), false end end
    end
end
